config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  root 'video_games#explore'
  get '/sitemap', to: 'static_pages#sitemap'


  # Static Pages
  match 'privacy' => 'static_pages#privacy', via: :get
  match 'about_us' => 'static_pages#about_us', via: :get

  get 'feed', :to => "feed#index"
  resources :video_games do 
    get :history, on: :member

  	resources :listings
    resources :critic_reviews
  end
  
  match 'select2_search' => 'video_games#select_search', :via => :get
  	
  resources :drafts do 
    post :accept, on: :member
    post :deny, on: :member
  end
  
  resources :users, only: [] do
      resources :shelves
  end
  
  resources :shelves, only: [:show]


  resources :shelved_games


  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    match 'users/omniuath_finish_signup' => 'users/omniauth_callbacks#finish_signup', via: :get
    match 'users/omniuath_create_signup' => 'users/omniauth_callbacks#create_signup', via: :post
  end



  resources :gifs, only: [:index]

  resources :franchises

  resources :series

  resources :platforms

  resources :game_modes

  resources :game_engines

  resources :ratings

  resources :genres

  resources :player_perspectives

  resources :companies

  resources :follows do 
    get :followers, on: :member
  end

  resources :questions do 
    resources :answers
  end 

  resources :lists do 
    resources :list_video_games
  end

  resources :users do 
    post 'mark_as_favorite/:video_game_id', to: 'users#mark_game_as_favorite', as: :mark_as_favorite
    post 'unmark_as_favorite', to: 'users#unmark_game_as_favorite', as: :unmark_as_favorite    

    post 'update_avatar', to: 'users#update_avatar'
    post 'remove_avatar', to: 'users#remove_avatar'
    post 'update_banner', to: 'users#update_banner'
    post 'remove_banner', to: 'users#remove_banner'


  end

  match 'leaderboard' => 'users#leaderboard', :via => :get
  match 'scorecard' => 'users#scorecard', :via => :get
  match 'mark_as_seen/:id' => 'rewards#mark_as_seen', via: :post
  match 'rewards/mark_all_as_seen' => 'rewards#mark_all_as_seen', via: :post

  resources :comments 

  resources :pages

  resources :groups do 
    resources :memberships, shallow: true do 
      post :approve, on: :member
      post :revoke, on: :member
      post :promote, on: :member
      post :demote, on: :member
    end
  end

  resources :friendships do
    post :accept, on: :member
    post :deny, on: :member
  end

  resources :member_reviews
  # Social Shit
  resources :posts
  resources :attachments, only: [:create, :destroy]

  resources :topics do 
    resources :topic_comments, shallow: true
  end


  resources :referrals, only: [:index, :show]

  get 'twitch/videos', :to => 'twitch#get_videos'


  get '/search/', to: 'search#index', as: 'search'


  # Shit for Notifications
  resources :notifications, only: [:show, :delete] do 
    post :mark_as_read
  end
  match 'mark_all_as_read' => 'notifications#mark_all_as_read', :via => :post


  resources :list_video_games, only: [:show]
  resources :answers, only: [:show]
  resources :likes, only: [:show]
  resources :contributions, only: [:show, :index] do 
      get :breakdown, on: :member
  end

  match 'like_thing', to: 'likes#like', via: :post
  match 'unlike_thing', to: 'likes#unlike', via: :delete
  
  match 'upvote_thing', to: 'votes#upvote', via: :post
  match 'unvote_thing', to: 'votes#unvote', via: :delete



  namespace :admin do
    root :to => 'dashboard#index'
    resources :blog_posts
    resources :blog_categories
    resources :users
  end

  resources :blog, only: [:index, :show]

  # match 'wikis' => 'wikis#index', via: [:get, :post, :put, :patch, :delete]  
  resources :wikis, except: [:show]
  match 'wikis/:id' => 'wikis#show', via: [:get, :post, :put, :patch, :delete]
  match 'wikis/:id/*path' => 'wikis#show', via: [:get, :post, :put, :patch, :delete]
  match 'store/*path' => 'store#index', via: [:get, :post, :put, :patch, :delete]
  match 'store' => 'store#index', via: [:get, :post, :put, :patch, :delete]
  post '/tinymce_assets' => 'tinymce_assets#create'


 scope '/api' do
    scope '/v1' do
      scope '/orders' do
        post '/' => 'api_orders#create'
      end
    end
  end

require "sidekiq/web"

mount Sidekiq::Web => "/sidekiq"

end

app/controllers/member_reviews_controller.rb
class MemberReviewsController < ApplicationController
	def create
		member_review = MemberReview.new(member_review_params)
		if(member_review.save)
			flash[:success] = "Woohooo Your totally awesome review has been saved and posted"
		else
			flash[:warning] = "Why does everyone help me"
		end
		redirect_back(fallback_location: root_path)
	end

	def index
		@user = User.friendly.find(params[:user_id])
	end

	def edit
		@member_review = MemberReview.find(params[:id])
		@video_game = @member_review.video_game
	end

	def update
		member_review = MemberReview.find(params[:id])
		member_review.assign_attributes(member_review_params)		
		if member_review.save
      		flash[:success] = "Updated Review"
      		redirect_to member_review.video_game
		else
      		flash[:error] = "Error Updating Your Review"
		    redirect_back(fallback_location: root_path)	
		end
	end


	def show
		@member_review = MemberReview.find(params[:id])
	end

	def destroy
		member_review = current_user.member_reviews.find_by_id(params[:id])
		if member_review.destroy
			flash[:success] = "You have succesfully eviscerated your review"
			redirect_to member_review.video_game
		else
			flash[:warning] = "Woops something went wrong you couldn't delete the review"
			redirect_back(fallback_location: root_path)	
		end
	end

	private
  	def member_review_params
    	params.require(:member_review).permit(:body, :user_id, :rating, :video_game_id)
  	end	
end

app/helpers/member_reviews_helper.rb
module MemberReviewsHelper
end

app/views/member_reviews/_form.html.erb
<div class="new-customer-review">
	<%= form_for object do |f| %>
		<div class="form-group">
			<%= f.label "What did you think?" %>
			<%= f.select :rating, ['',1, 2, 3, 4, 5, 6, 7, 8, 9, 10], {}  %>
		</div>

		<div class="form-group">
			<%= f.text_area :body, class: "tinymce" %>
		</div>

		<%= f.hidden_field :user_id, value: current_user.id %>
		<%= f.hidden_field :video_game_id, value: @video_game.id %>
		<%= tinymce %>

		<%= f.submit "Post Review", class: "btn btn-success" %>
	<% end %>
</div>

app/views/member_reviews/_member_review.erb
<div class="member_review">
	<%= member_review.user.username %>
	<%= link_to "Edit", edit_member_review_url(member_review) if current_user == member_review.user %>
	<div>
		<%= generateStars(member_review.rating, 10).html_safe %>
	</div>
	<%= member_review.body.html_safe %>
</div>

app/views/member_reviews/_reviews.html.erb
<div class="customer-reviews">
	<h4>Member Reviews</h4>

	<%= render partial: "member_reviews/form", locals: {object: MemberReview.new} if current_user %>
	<%= render video_game.member_reviews %>
</div>

app/views/member_reviews/edit.html.erb
<div class="container mt-5">
	<%= render partial: "form", locals: {object: @member_review} %>
	<!-- Or Delete -->
	<%= link_to 'Destroy',  member_review_path(@member_review),
    data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger mt-3" %>
</div>

app/views/member_reviews/index.html.erb
<div class="container mt-5">
	<div class="col-lg-10 offset-1">
		<h1><%= link_to @user.username, @user %> Member Reviews</h1>	
		<% @user.member_reviews.each do |member_review| %>		
			<div class="card mb-4">
				<div class="card-body">
					<div class="row">
						<div class="col-lg-2">
							<%= image_tag member_review.video_game.box_art, class: "img-fluid" %>
						</div>
						<div class="col-lg-10">
							<%= link_to member_review.video_game.name, member_review.video_game %>
							<%= link_to sanitize(member_review.body), member_review, class: "text-dark" %>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/member_reviews/show.html.erb
<% video_game = @member_review.video_game %>
<div class="container mt-5">
	<div class="row">
		<div class="box-art col-lg-2">
			<%= image_tag video_game.box_art, class: "img-fluid" %>
		</div>
		<div class="game-info col-lg-10">

			<div><h1><%= link_to "#{@member_review.user.username} review of #{video_game.name}", video_game %></h1>></div>
			<% unless video_game.description.empty? %>
				<div class="mt-3">
					<%= video_game.description %>
				</div>
			<% end %>			
		</div>
	</div>
	<hr>
	<div class="reviewer">
		<div class="avatar pull-left">
			<%= image_tag @member_review.user.avatar, size: "50", class: "mr-4" %>
		</div>
		<div class="user-info">
			<%= link_to @member_review.user.username, @member_review.user %></br>
			<p class="pull-right font-weight-bold"><%= @member_review.rating / 10.0 * 100  %> out of 100</p>
			<span class="text-muted"><%= time_ago_in_words @member_review.created_at %></span>
		</div>
	</div>
	<div class="review mt-3">
		<%= raw @member_review.body %>
	</div>
</div>