config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  root 'video_games#explore'
  get '/sitemap', to: 'static_pages#sitemap'


  # Static Pages
  match 'privacy' => 'static_pages#privacy', via: :get
  match 'about_us' => 'static_pages#about_us', via: :get

  get 'feed', :to => "feed#index"
  resources :video_games do 
    get :history, on: :member

  	resources :listings
    resources :critic_reviews
  end
  
  match 'select2_search' => 'video_games#select_search', :via => :get
  	
  resources :drafts do 
    post :accept, on: :member
    post :deny, on: :member
  end
  
  resources :users, only: [] do
      resources :shelves
  end
  
  resources :shelves, only: [:show]


  resources :shelved_games


  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    match 'users/omniuath_finish_signup' => 'users/omniauth_callbacks#finish_signup', via: :get
    match 'users/omniuath_create_signup' => 'users/omniauth_callbacks#create_signup', via: :post
  end



  resources :gifs, only: [:index]

  resources :franchises

  resources :series

  resources :platforms

  resources :game_modes

  resources :game_engines

  resources :ratings

  resources :genres

  resources :player_perspectives

  resources :companies

  resources :follows do 
    get :followers, on: :member
  end

  resources :questions do 
    resources :answers
  end 

  resources :lists do 
    resources :list_video_games
  end

  resources :users do 
    post 'mark_as_favorite/:video_game_id', to: 'users#mark_game_as_favorite', as: :mark_as_favorite
    post 'unmark_as_favorite', to: 'users#unmark_game_as_favorite', as: :unmark_as_favorite    

    post 'update_avatar', to: 'users#update_avatar'
    post 'remove_avatar', to: 'users#remove_avatar'
    post 'update_banner', to: 'users#update_banner'
    post 'remove_banner', to: 'users#remove_banner'


  end

  match 'leaderboard' => 'users#leaderboard', :via => :get
  match 'scorecard' => 'users#scorecard', :via => :get
  match 'mark_as_seen/:id' => 'rewards#mark_as_seen', via: :post
  match 'rewards/mark_all_as_seen' => 'rewards#mark_all_as_seen', via: :post

  resources :comments 

  resources :pages

  resources :groups do 
    resources :memberships, shallow: true do 
      post :approve, on: :member
      post :revoke, on: :member
      post :promote, on: :member
      post :demote, on: :member
    end
  end

  resources :friendships do
    post :accept, on: :member
    post :deny, on: :member
  end

  resources :member_reviews
  # Social Shit
  resources :posts
  resources :attachments, only: [:create, :destroy]

  resources :topics do 
    resources :topic_comments, shallow: true
  end


  resources :referrals, only: [:index, :show]

  get 'twitch/videos', :to => 'twitch#get_videos'


  get '/search/', to: 'search#index', as: 'search'


  # Shit for Notifications
  resources :notifications, only: [:show, :delete] do 
    post :mark_as_read
  end
  match 'mark_all_as_read' => 'notifications#mark_all_as_read', :via => :post


  resources :list_video_games, only: [:show]
  resources :answers, only: [:show]
  resources :likes, only: [:show]
  resources :contributions, only: [:show, :index] do 
      get :breakdown, on: :member
  end

  match 'like_thing', to: 'likes#like', via: :post
  match 'unlike_thing', to: 'likes#unlike', via: :delete
  
  match 'upvote_thing', to: 'votes#upvote', via: :post
  match 'unvote_thing', to: 'votes#unvote', via: :delete



  namespace :admin do
    root :to => 'dashboard#index'
    resources :blog_posts
    resources :blog_categories
    resources :users
  end

  resources :blog, only: [:index, :show]

  # match 'wikis' => 'wikis#index', via: [:get, :post, :put, :patch, :delete]  
  resources :wikis, except: [:show]
  match 'wikis/:id' => 'wikis#show', via: [:get, :post, :put, :patch, :delete]
  match 'wikis/:id/*path' => 'wikis#show', via: [:get, :post, :put, :patch, :delete]
  match 'store/*path' => 'store#index', via: [:get, :post, :put, :patch, :delete]
  match 'store' => 'store#index', via: [:get, :post, :put, :patch, :delete]
  post '/tinymce_assets' => 'tinymce_assets#create'


 scope '/api' do
    scope '/v1' do
      scope '/orders' do
        post '/' => 'api_orders#create'
      end
    end
  end

require "sidekiq/web"

mount Sidekiq::Web => "/sidekiq"

end

app/models/topic.rb
class Topic < ApplicationRecord
	include Notifiable
	# Rewards
	include Rewardable
	def get_points
		45
	end
	# End of Rewards

	is_impressionable	
	belongs_to :user
	belongs_to :topicable, polymorphic: true
	has_many :topic_comments

	def get_affected_users
		users = []

		# Users that follow the topicable
		users << User.includes(:follows).where('follows.followable_id' => topicable_id).where('follows.followable_type' => topicable_type).pluck(:id)

		# Users that have made a topic comment
		users << topic_comments.pluck(:user_id)

		# Users that Have commented on a topic comment
		users << topic_comments.collect{|topic_comment| topic_comment.comments}.flatten.pluck(:user_id)

		# User that have liked a topic comment comment
		users << topic_comments.collect{|topic_comment| topic_comment.comments}.flatten.collect{|comment| comment.likes}.flatten.pluck(:user_id)

		users.flatten.uniq
	end

	#  How to get affected users after record is deleted?

	def create_notifications
	    current_user = User.current
	    if transaction_include_any_action?([:create])
			message = "#{current_user.username} has created a new topic about #{topicable.name}."
	    elsif transaction_include_any_action?([:update])
			message = "#{current_user.username} has modied a new topic about #{topicable.name}."
	    end
		GenerateNotificationsWorker.perform_async(self.class.name, self.id, message, current_user.id)	    
	end		
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
   	before_action :authenticate_user! #-> routes to the login / signup if not authenticated	
	before_action :is_owner?, only: [:edit, :update, :destroy]
	
	def new
		if params[:topicable_type] && params[:topicable_id]
			model = params[:topicable_type].constantize.find(params[:topicable_id])
			@topic = model.topics.new		
		else
			@topic = Topic.new
		end
	end

	def create
		topic = Topic.new(topic_params)
		topic.user = current_user
		topic.is_poll = false
		if topic.save
			flash[:success] = "Topic successfully saved"
			redirect_to topic
		else
			flash[:error] = "Could not save topic"
			redirect_back(fallback_location: root_path)
		end
	end

	def edit
		@topic = Topic.find(params[:id])
	end

	def update
		topic = Topic.find(params[:id])
		topic.assign_attributes(topic_params)
		
		if topic.save
			redirect_to topic
		else
			redirect_back(fallback_location: root_path)
		end
	end

	def show
		@topic = Topic.find(params[:id])
		@topic_comments = @topic.topic_comments.order(created_at: :desc).page params[:page]
	end

	def index 
		if params[:topicable_type] and params[:topicable_id]
			@topicable = params[:topicable_type].constantize.find(params[:topicable_id])
			@topics = @topicable.topics
		else
			@topics = Topic.all
		end


	end

	def destroy
		topic = Topic.find(params[:id])
		if topic.destroy
			flash[:success] = "Topic Successfully Deleted"
			redirect_to topic.topicable
		else
			flash[:danger] = topic.errors.full_messages
			redirect_to 'edit'
		end

	end

private
	
	def topic_params
	    params.require(:topic).permit(:topic, :topicable_type, :topicable_id)
	end	

	def is_owner? 
		topic = Topic.find(params[:id])
		
		if topic.user != current_user
			flash[:warning] = "You are not the owner of #{topic.name}."
			redirect_back(fallback_location: root_path)				
		end
	end	
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>

	<%= f.hidden_field :is_poll, value: false %>
	<% if @topic.topicable %>
		<%= f.hidden_field :topicable_id, value: @topic.topicable.id%>
		<%= f.hidden_field :topicable_type, value: @topic.topicable.class.name%>	
	<% else %>
		<div class="form-group">
			<%= f.label :topicable_id, "Video Game" %>
			<%= f.collection_select :topicable_id, [], :id, :name, {}, {multiple: false, class: "form-control"} %>
			<%= f.hidden_field :topicable_type, value: "VideoGame" %>	
		</div>
	<% end %>
	
	<div class="form-group mt-3">
		<%= f.label :topic %>
		<%= f.text_area :topic, class: "form-control" %>
	</div>

	<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/topics/_table.html.erb
<%= render object.topics %>

app/views/topics/_topic.html.erb
<div class="list-group-item">
	<div class="row">
		<div class="col-2">
			<%= link_to topic do %>	
				<%= image_tag topic.user.avatar, class: "img-fluid" %>
			<% end %>	
		</div>
		<div class="col-10">
			<div class="topic-title">
				<h5 class="mb-1"><%= link_to topic.topic, topic %></h5>
			</div>
			<div class="topic-info">
				<span class="topic-author">By: <%= link_to topic.user.username, topic.user %></span>
				<span class="separator">∙</span>
				<span class="topic-answer-count"><%= topic.topic_comments.count %> Answers</span>
				<% if topic.topic_comments.any? %>
					<span class="separator">∙</span>
					<time datetime="2018-09-10T08:21:05-07:00">
						<%= "#{time_ago_in_words(topic.topic_comments.last.created_at)} ago" if  topic.topic_comments.last %>
					</time>
				<% end %>
			</div>				
		</div>
	</div>
</div>

app/views/topics/_topics.html.erb
<div class="topics">
	<h4><%= link_to "Discuss This Game", topics_path(topicable_id: object.id, topicable_type: object.class.name) %> </h4>
	<%= link_to "New Topic", new_topic_path(topicable_id: object.id, topicable_type: object.class.name), class: "btn btn-success mb-3" %>
	<div class="list-group">
		<%= render object.topics.limit(5) %>
	</div>
	
	<% if object.topics.count > 5 %>
		<%= link_to "View More...", topics_path(topicable_id: object.id, topicable_type: object.class.name), class: "pull-right" %> 
	<% end %>

</div>

app/views/topics/edit.html.erb
<div class="container mt-5">
	<%= render "form" %>
	<%= link_to "Delete Topic", topic_url(@topic), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mt-5" %>

</div> 

app/views/topics/index.html.erb
<div class="container">
	<% if @topicable %>
		<h1><%= link_to @topicable.name, @topicable %> All Topic Threads</h1>
		<div class="discussion row">
			<div class="discussion-image col-lg-2">
				<% object = @topicable %>
				<%= link_to object do %>
					<%= image_tag object.box_art, class: "img-fluid" %></br>
					<%= object.name %>
				<% end %>
					
				<%= link_to "New Topic", new_topic_path(topicable_id: object.id, topicable_type: object.class.name ), class: "btn btn-success btn-block" %>
			</div>
			<div class="discussion-body col-lg-10">
				<%= render partial: "table", locals: {object: object} %>
			</div>
		</div>	
	<% else %>
		<h1>Video Game Topics</h1>	
		<%= link_to "New Topic", new_topic_path, class: "btn btn-success mb-3" %>
		<% @topics.select(:topicable_id, :topicable_type).distinct.each do |topicable| %>
			<div class="discussion row">
				<div class="discussion-image col-lg-2">
					<% object = topicable.topicable_type.constantize.find(topicable.topicable_id) %>
					
					<%= link_to object do %>
						<%= image_tag object.box_art, class: "img-fluid" %></br>
						<%= object.name %>
					<% end %>
					
					<%= link_to "New Topic About #{object.name}", new_topic_path(topicable_id: object.id, topicable_type: object.class.name ), class: "btn btn-success btn-block" %>
				</div>
				<div class="discussion-body col-lg-10">
					<%= render partial: "table", locals: {object: object} %>
				</div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/topics/new.html.erb
<div class="container">
	<h1>Post A New Discussion Topic</h1>
	<% if @topic.topicable %>
		This topic is about <%= link_to @topic.topicable.name, @topic.topicable %>
	<% end %>

	<%= render "form" %>
</div>

app/views/topics/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3 col-sm-12">
			<div class="box-art">
				<%= image_tag @topic.topicable.box_art, class: "img-fluid" %>
			</div>				
		</div>
		<div class="col-lg-9 col-sm-12">
			<div class="topic-info">
				<h1><%= link_to "#{@topic.topicable.name} Discussion", topics_path(topicable_id:  @topic.topicable.id, topicable_type:  @topic.topicable.class.name ) %></h1>
				<div id="topic-text">
					Topic: <%= @topic.topic %></br>
					<span class="topic-user">
						By: <%= link_to @topic.user.username, @topic.user %>
					</span></br>
					<span id="topic-views"><%= "#{pluralize(@topic.impressionist_count, 'view')}" %></span>
					<% if user_signed_in? && @topic.user == current_user %>
						<div><%= link_to "Edit", edit_topic_path(@topic), class: "btn btn-secondary" %></div>
					<% end %>
				</div>			
			</div>			
		</div>
	</div>
	<div class="pagination">
		<%= paginate @topic_comments %>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<%= render "topic_comments/form" %>
		</div>
	</div>
	
	<%= render @topic_comments %>

 	<div class="pagination">
		<%= paginate @topic_comments %>
	</div>
</div>