config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  root 'video_games#explore'
  get '/sitemap', to: 'static_pages#sitemap'


  # Static Pages
  match 'privacy' => 'static_pages#privacy', via: :get
  match 'about_us' => 'static_pages#about_us', via: :get

  get 'feed', :to => "feed#index"
  resources :video_games do 
    get :history, on: :member

  	resources :listings
    resources :critic_reviews
  end
  
  match 'select2_search' => 'video_games#select_search', :via => :get
  	
  resources :drafts do 
    post :accept, on: :member
    post :deny, on: :member
  end
  
  resources :users, only: [] do
      resources :shelves
  end
  
  resources :shelves, only: [:show]


  resources :shelved_games


  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    match 'users/omniuath_finish_signup' => 'users/omniauth_callbacks#finish_signup', via: :get
    match 'users/omniuath_create_signup' => 'users/omniauth_callbacks#create_signup', via: :post
  end



  resources :gifs, only: [:index]

  resources :franchises

  resources :series

  resources :platforms

  resources :game_modes

  resources :game_engines

  resources :ratings

  resources :genres

  resources :player_perspectives

  resources :companies

  resources :follows do 
    get :followers, on: :member
  end

  resources :questions do 
    resources :answers
  end 

  resources :lists do 
    resources :list_video_games
  end

  resources :users do 
    post 'mark_as_favorite/:video_game_id', to: 'users#mark_game_as_favorite', as: :mark_as_favorite
    post 'unmark_as_favorite', to: 'users#unmark_game_as_favorite', as: :unmark_as_favorite    

    post 'update_avatar', to: 'users#update_avatar'
    post 'remove_avatar', to: 'users#remove_avatar'
    post 'update_banner', to: 'users#update_banner'
    post 'remove_banner', to: 'users#remove_banner'


  end

  match 'leaderboard' => 'users#leaderboard', :via => :get
  match 'scorecard' => 'users#scorecard', :via => :get
  match 'mark_as_seen/:id' => 'rewards#mark_as_seen', via: :post
  match 'rewards/mark_all_as_seen' => 'rewards#mark_all_as_seen', via: :post

  resources :comments 

  resources :pages

  resources :groups do 
    resources :memberships, shallow: true do 
      post :approve, on: :member
      post :revoke, on: :member
      post :promote, on: :member
      post :demote, on: :member
    end
  end

  resources :friendships do
    post :accept, on: :member
    post :deny, on: :member
  end

  resources :member_reviews
  # Social Shit
  resources :posts
  resources :attachments, only: [:create, :destroy]

  resources :topics do 
    resources :topic_comments, shallow: true
  end


  resources :referrals, only: [:index, :show]

  get 'twitch/videos', :to => 'twitch#get_videos'


  get '/search/', to: 'search#index', as: 'search'


  # Shit for Notifications
  resources :notifications, only: [:show, :delete] do 
    post :mark_as_read
  end
  match 'mark_all_as_read' => 'notifications#mark_all_as_read', :via => :post


  resources :list_video_games, only: [:show]
  resources :answers, only: [:show]
  resources :likes, only: [:show]
  resources :contributions, only: [:show, :index] do 
      get :breakdown, on: :member
  end

  match 'like_thing', to: 'likes#like', via: :post
  match 'unlike_thing', to: 'likes#unlike', via: :delete
  
  match 'upvote_thing', to: 'votes#upvote', via: :post
  match 'unvote_thing', to: 'votes#unvote', via: :delete



  namespace :admin do
    root :to => 'dashboard#index'
    resources :blog_posts
    resources :blog_categories
    resources :users
  end

  resources :blog, only: [:index, :show]

  # match 'wikis' => 'wikis#index', via: [:get, :post, :put, :patch, :delete]  
  resources :wikis, except: [:show]
  match 'wikis/:id' => 'wikis#show', via: [:get, :post, :put, :patch, :delete]
  match 'wikis/:id/*path' => 'wikis#show', via: [:get, :post, :put, :patch, :delete]
  match 'store/*path' => 'store#index', via: [:get, :post, :put, :patch, :delete]
  match 'store' => 'store#index', via: [:get, :post, :put, :patch, :delete]
  post '/tinymce_assets' => 'tinymce_assets#create'


 scope '/api' do
    scope '/v1' do
      scope '/orders' do
        post '/' => 'api_orders#create'
      end
    end
  end

require "sidekiq/web"

mount Sidekiq::Web => "/sidekiq"

end

app/models/answer.rb
class Answer < ApplicationRecord
	include Likeable
	include Notifiable
	# Rewards
	include Rewardable
  	def get_points
  		45
  	end
	# End of Rewards

	belongs_to :question
	belongs_to :user
	has_many :comments, as: :commentable
	is_impressionable

	def get_affected_users
		users = []

		# Question User		
		users << question.user_id
		
		# Other Answer User		
		users << question.answers.pluck(:user_id)
		
		# Question Like User
		users << question.likes.pluck(:user_id)

		# Answer Like User 
		users << question.answers.collect{|answer| answer.likes}.flatten.pluck(:user_id)
		
		# Answer Comment User	
		users << question.answers.collect{|answer| answer.comments}.flatten.pluck(:user_id)
		
		# Answer Comments Likes
		users << question.answers.collect{|answer| answer.comments}.flatten.collect{|comment| comment.likes }.flatten.pluck(:user_id)

		users.flatten.uniq
	end

	#  How to get affected users after record is deleted?

	def create_notifications
	    current_user = User.current
	    if transaction_include_any_action?([:create])
			message = "#{current_user.username} has submitted a new answer."
	    elsif transaction_include_any_action?([:update])
			message = "#{current_user.username} has edited their answer."
	    end
		GenerateNotificationsWorker.perform_async(self.class.name, self.id, message, current_user.id)
	end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_action :authenticate_user! #-> routes to the login / signup if not authenticated	
	before_action :is_owner?, only: [:edit, :update, :destroy]

	def create
		answer = Answer.new(answer_params)
		answer.user = current_user
		answer.question = Question.find(params[:question_id])
		if answer.save
      		flash[:success] = "Saved Answer"
		else
      		flash[:error] = "error with saving answer"
		end
	    redirect_back(fallback_location: root_path)

	end

	def edit
		@question = Question.find(params[:question_id])
		@answer = Answer.find(params[:id])
	end

	def update
		answer = Answer.find(params[:id])
		answer.assign_attributes(answer_params)		
		if answer.save
      		flash[:success] = "Updated Answer"
      		redirect_to answer.question
		else
      		flash[:error] = "error with saving answer"
      		redirect_back(fallback_location: root_path)      		
		end
	end 

	def show
		answer = Answer.find(params[:id])
		redirect_to answer.question
	end

	def destroy
		answer = Answer.find(params[:id])
		if answer.destroy
			flash[:success] = "Successfully destroyed answer"
		else
			flash[:danger] = answer.errors.full_messages			
		end
		redirect_to answer.question

	end

private
	def answer_params
	    params.require(:answer).permit(:answer, :question_id)		
	end

	def is_owner? 
		answer = Answer.find(params[:id])
		
		if answer.user != current_user
			flash[:warning] = "You are not the owner of this question."
			redirect_back(fallback_location: root_path)				
		end
	end	
end

app/views/answers/_answer.html.erb
<div class="card community-answer mb-3" id="<%= "answer-#{answer.id}" %>">
	<div class="card-header">
		<%= link_to answer.user.username, answer.user if answer.user %>
		<span class="float-right" ><%= answer.created_at.strftime("%B %d, %Y %I:%M%p") %></span>
	</div>
	<div class="card-body">
		<div class="answerer-user-icon">
			<%= image_tag answer.user.avatar, size: "50", class: "avatar float-left mr-3" if answer.user %>
		</div>
		<span class="community-answer-text"><%= answer.answer %></span>			

		<% if user_signed_in? &&  current_user == answer.user %>
			<div class="pull-right admin-actions">
				<div class="btn-group">
				<button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<%= fa_icon "ellipsis-h" %>
				</button>
				<div class="dropdown-menu">
					<%= link_to "Edit", edit_question_answer_path(answer.question, answer), class: "dropdown-item" %>
				</div>
				</div>			
			</div>	
		<% end %>
	</div>
	<div class="card-actions text-muted ml-3">
		<ul class="list-inline">
			<li class="list-inline-item"><%= pluralize(answer.likes.count, 'like') %></li>
			<li class="list-inline-item"><%= render partial: "likes/button", locals: {likeable: answer} %></li>
			<li class="list-inline-item"><%= time_ago_in_words answer.created_at %></li>
		</ul>
	</div>

	<div class="community-answer-footer">
		<%= render partial: "comments/comments", locals: {comments: answer.comments.order(created_at: :desc), commentable: answer} %>
	</div>
</div>

app/views/answers/_form.html.erb
<div class="my-3">
<%= form_for [question, answer] do |f| %>
  	<div class="form-group">
		<%= f.text_area :answer, placeholder: "Answer this question", class: "form-control" %>
	</div>
	<%= f.submit "Submit Answer", class: "btn btn-primary" %>
<% end %>
</div>

app/views/answers/edit.html.erb
<div class="container mt-5">
	<%= render partial: 'form', locals: {question: @question, answer: @answer} %>
	<%= link_to 'Destroy Answer',  question_answer_path(@question, @answer), data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger pull-right" %>
</div>